parameters:
  - name: projectDirectory
    type: string
    default: ""

steps:
  - template: ../tasks/install-node-task.yaml
    parameters:
      projectDirectory: ${{ parameters.projectDirectory }}
      authenticateNpm: false
      authenticateYarn: false
  - template: ../tasks/cache-npm-task.yaml
    parameters:
      projectDirectory: ${{ parameters.projectDirectory }}
      cacheVersion: $(CacheVersion)
  - template: ../tasks/pwsh-task.yaml
    parameters:
      projectDirectory: ${{ parameters.projectDirectory }}
      scriptFile: test.ps1
