parameters:
  - name: projectDirectory
    type: string
    default: ""

stages:
  - stage: test
    displayName: Test
    jobs:
      - job: Test
        variables:
          # # TODO: Re-enable once we fix cache key
          # # Defines `CacheVersion` (for use with the various cache tasks).
          # - name: CacheVersion
          #   value: $[ format('{0:yyyy}.{0:MM}', pipeline.startTime) ]
          - group: Cloudflare Storage Passwords
          - group: SaladCloud API Keys
        steps:
          - template: ../steps/test-steps.yaml
            parameters:
              projectDirectory: ${{ parameters.projectDirectory }}
